---
- name: "Setup.yml"
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
  - name: Colorize root shell prompt
    lineinfile:
      path: /root/.bashrc
      line: 'export PS1="\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\h:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"'
      state: present

  - name: Disable GSSAPIAuthentication
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^GSSAPIAuthentication"
      line: "GSSAPIAuthentication no"
      state: present

  - name: Update CA bundle (Rocky)
    get_url:
      url: https://curl.haxx.se/ca/cacert.pem
      dest: /etc/pki/tls/certs/ca-bundle.crt
      force: yes
    when: ansible_distribution == "Rocky"

  - name: Install epel repo (Rocky)
    dnf:
      name: "epel-release"
      state: latest
    when: ansible_distribution == "Rocky"

  - name: Upgrade all packages (Rocky)
    dnf:
      name: "*"
      state: latest
    when: ansible_distribution == "Rocky"

  - name: Install packages (Rocky)
    dnf:
      name: 
      - bash-completion
      - curl
      - git
      - rsync
      - screen
      - tcpdump
      - wget
      - nano
      - net-snmp 
      - net-snmp-libs
      - net-snmp-utils
      state: latest      
    when: ansible_distribution == "Rocky"

  - name: Install open-vm-tools (Rocky)
    dnf:
      name: open-vm-tools
      state: latest
    when:
      - ansible_distribution == "Rocky"
      - ansible_virtualization_type == "VMware"
