name: 'Packer vSphere Rocky 9.3 CI Template Generator'

env:
  # vSphere password used for authentication
  VCENTER_PASSWORD: ${{ secrets.VSPHERE_PASSWORD }}
  # Deployment Password
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

on:
  workflow_dispatch:
  
permissions:
  contents: read
  
jobs:
  packer:
    name: 'Packer Build Pipeline'
    runs-on: [self-hosted, devops]
    environment: production  
    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
 
    - name: Packer Setup
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"
        
    - name: Run init        
      working-directory: ./VMware/Rocky-9.3
      run: packer init rocky.pkr.hcl

    - name: Run validate
      working-directory: ./VMware/Rocky-9.3
      run: packer validate -var-file=variables.pkrvars.hcl rocky.pkr.hcl
      env:
        PKR_VAR_vcenter_password: ${{ env.VCENTER_PASSWORD }}
        PKR_VAR_ssh_password: ${{ env.SSH_PASSWORD }}

    - name: Run build
      working-directory: ./VMware/Rocky-9.3
      run: packer build -var-file=variables.pkrvars.hcl rocky.pkr.hcl
      env:
        PKR_VAR_vcenter_password: ${{ env.VCENTER_PASSWORD }}
        PKR_VAR_ssh_password: ${{ env.SSH_PASSWORD }}